version: '2.1'

services:
  marketing:
    image: "sunshower/marketing:${MARKETING_VERSION}"
    volumes:
      - ~/.sunshower/certs/server.crt:/etc/nginx/ssl/server.crt:ro
      - ~/.sunshower/certs/server.key:/etc/nginx/ssl/server.key:ro

  proxy:
    extends:
      file: common-services.yml
      service: proxy
    links:
      - marketing
      - ui
      - web-services
    ports:
      - 80:80
      - 443:443


  ui:
    extends:
      file: common-services.yml
      service: ui



  web-services:
    extends:
      file: common-services.yml
      service: web-services
    links:
      - marketing
      - db


  db:
    extends:
      file: common-services.yml
      service: db
